
2018-08-08 21:02:42,225 ERROR django.request Internal Server Error: /dspace/
Traceback (most recent call last):
  File "/home/deployer/pub_download3/lib/python3.4/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/deployer/pub_download3/lib/python3.4/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/deployer/pub_download3/lib/python3.4/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/deployer/pub_download3/publications/gug/views.py", line 50, in dspace_detail
    dspace_record = Dspace.objects.get(id_dspace=id_dspace)
  File "/home/deployer/pub_download3/lib/python3.4/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/deployer/pub_download3/lib/python3.4/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
gug.models.DoesNotExist: Dspace matching query does not exist.
